assets/examples/from.yml
assets/examples/to.yml
cmd/between.go
cmd/root.go
core/compare_test.go
core/core.go
core/core_suite_test.go
core/core_test.go
core/json_test.go
core/output.go
core/output_test.go
core/yaml_test.go

Use forks of https://github.com/HeavyWombat/color and https://github.com/HeavyWombat/yaml.
Rework of Diff and Details structs.
Rework of test cases.
Implementation of side-by-side output.
Initial draft of `between` functionality.

Rework of internals for initial compare functionality

---

.gitignore
.travis.yml
Makefile

Add required steps to upload code coverage statistics to codecov.io.

Add codecov to dyff

---

.travis.yml

Add Go version 1.12 to Travis configuration.

Add Go version 1.12

---

pkg/v1/dyff/core.go
pkg/v1/dyff/core_suite_test.go
pkg/v1/dyff/output_human.go
pkg/v1/dyff/restructure.go

Fix findings by `staticcheck` tool.

Fix findings of staticcheck

---

scripts/compile-version.sh

Add output of `file` and `shasum` commands to the build output.

Add further build details to output

---

go.mod
go.sum
pkg/v1/dyff/core.go
pkg/v1/dyff/core_test.go
pkg/v1/dyff/output_brief.go
pkg/v1/dyff/output_human.go

Replace own Plural function with the one from the `gonvenience` package.

Use Plural function of gonvenience package

---

scripts/compile-version.sh

Remove building a windows binary.

Remove windows build

---

.travis.yml
assets/colors/dyff.expected
assets/colors/from.yml
assets/colors/to.yml
pkg/v1/dyff/core_suite_test.go
pkg/v1/dyff/output_human_test.go

Add test case to check the diff output including the colors for a semi-complex
BOSH manifest based delta report.

Add test to check colors

---

.travis.yml
go.mod

Set Go version to 1.15 in module file and in Travis configuration.

Bump to Go version 1.15

---

.travis.yml

Bump version of golang-dev-tools used in Travis.

Bump golang dev tools in Travis

---

go.sum
internal/cmd/between.go
internal/cmd/common.go
pkg/dyff/core.go

This adds optional k8s entity discussion.

k8s: Add kubernetes metadata name detection

---

go.sum
internal/cmd/between.go
internal/cmd/common.go
pkg/dyff/core.go

Add optional k8s object detection.

---

.github/workflows/release.yml
.goreleaser.yml

Add `snapcrafts` section to GoReleaser.
Add step to install `snapcraft` to GitHub Action release workflow.

Add snap build and upload

---

scripts/download-latest.sh

Introduce loop to check for a suitable install location.

Simplify directory check

---

.goreleaser.yml

Remove obsolete `netgo` build tag.

Remove `netgo` build tag

---

assets/issues/issue-217/datestring.yml
go.mod
go.sum
internal/cmd/cmds_test.go

Fixes #217
Bump `github.com/gonvenience/neat` to pick up timestamp parsing fix.
Add test case based on user feedback.

Fix timestamp parse issue in JSON command

---

assets/kubernetes-configmaps/expected-dyff-spruce.human
assets/kubernetes-configmaps/from.yml
assets/kubernetes-configmaps/to.yml
pkg/dyff/core.go
pkg/dyff/output_human.go
pkg/dyff/output_human_test.go

Fixes #171
Introduce new code to create a more human friendly multiline text output.
6c3247f Introduce multiline text difference output
80eba8f Add example YAMLs for multiline differences

Add multiline text differences output

---

pkg/dyff/colors.go
pkg/dyff/output_human.go

output
Attempting to address https://github.com/homeport/dyff/issues/225
Happy to add additional tests on request :)

Fix assumptions about text being markdown by default for multiline

---

cmd/dyff/main.go
go.mod
internal/cmd/cmds_test.go
internal/cmd/common.go
internal/cmd/json.go
internal/cmd/root.go
internal/cmd/yaml.go

Use standard library replacements.
Refactor error with exit code setup to not use context error.

Remove `wrap` import

---

README.md

Add a repology badge to show the packaging status.

doc: Add packaging status, document FreeBSD install
