- internal/cmd/between.go
- pkg/dyff/compare_test.go
- pkg/dyff/core.go
- pkg/dyff/core_suite_test.go
- pkg/dyff/core_test.go
- pkg/dyff/input.go
- pkg/dyff/output_human.go
Add flags and implementation code to support changing the root level
of a given input file, or both. Depending on the actual object that
is referenced by the path that serves as the new root level, there
are use cases where a list should be translated into documents, or
where the list is used as the root level itself.
This should fix #3
> Implement change root flag

- assets/issues/issue-38/from.yml
- assets/issues/issue-38/to.yml
- go.sum
- pkg/v1/dyff/compare_test.go
- pkg/v1/dyff/core.go
- pkg/v1/dyff/core_suite_test.go
- pkg/v1/dyff/output_human_test.go
Rework `getIdentifierFromNamedLists` to check not just the number of keys in
the list, but more precisely the number of unique entries. This is to detect
lists that have a `name` key in each entry that does not have unique values.
Improve flaky test where the path style rendering option was not reset
correctly for each new test section.
This commit should fix #38.
> Fix identifier detection in named-entry lists

- internal/cmd/between.go
- internal/cmd/cmd_suite_test.go
- internal/cmd/cmds_test.go
There are still use cases that are not covered by tests.
Add test case that uses `--chroot` flag.
Add test case that checks error condition for `--chroot` in `from`.
Add test case that checks error condition for `--chroot` in `to`.
> Add more test cases for between command

- README.md
This PR fixes `go get` example in README.
Since 57ca16e, `go get`'s path looks like it should be `github.com/homeport/dyff/cmd/dyff`.
> fix path for `go get` in README

- README.md
Works rather well but unfortunately dyff does not allow hiding header with ASCII graphics dyff logo.
This header is displayed each change when browsing `git log --ext-diff -u` and takes quite much space.
> Example of embedding dyff into git

- internal/cmd/between.go
- internal/cmd/cmds_test.go
- pkg/dyff/compare_test.go
- pkg/dyff/core.go
- pkg/dyff/core_suite_test.go
- pkg/dyff/output_human.go
- pkg/dyff/output_human_test.go
Based on feedback in #108, there are use cases where the order changes
in a list are not important to be reported. It should be possible to
ignore changes to the order of a list.
Add flag to ignore order changes for the `between` command.
Add new test case to verify new command flag.
Add global option in `dyff` package to disable order change detection.
Introduce short circuit to bypass the order change detection.
Refactor return statement for named entry lists to unify the style.
> Add ignore order changes flag

- pkg/dyff/output_human.go
Hey appreciate all the awesome work that's been done on dyff, really getting some great use out of it.
I ran into two little issues however that I wanted to address:
- The first is that strings that have format specifiers in them get corrupted in the table style strings, i.e. `cool-string%s` displays as `cool-string%!s(MISSING)`, I think that just not using the string that needs to be colorized as the format string is sufficient, but I might be missing an edge case.
- The second is that reordering of more complicated nested object don't really show any output besides something like
```
⇆ order changed
- ,
+ ,
```
I think it's because the nodes in question are not terminal and therefore don't have string values. I borrowed the yamlString method to account for those cases.
Let me know if …
> Fix format specifier missing errors in strings in tables and missing objects during order change

- README.md
Fixes #158
References https://github.com/kubernetes/kubectl/issues/937, https://github.com/kubernetes/kubectl/commit/bafd13fd9fe4c980c250ec865310ebc31622b745
Add minimum version required.
Explain workaround for older `kubectl` versions.
> Clarify `kubectl diff` usage (#158)

- .goreleaser.yml
Fixes #194 (hopefully)
Add `system-files` plug to snapcrafts section with read-only access to `/tmp`.
> Add `system-files` plug

- scripts/download-latest.sh
Adds an additional filter to fetch the latest release with assets.
Fixes the usage in combination with pre-releases that typically do not have assets yet.
> Fixes downloader to get fetch non-empty release

- internal/cmd/between.go
- internal/cmd/common.go
- pkg/dyff/compare_test.go
- pkg/dyff/reports.go
Fix https://github.com/homeport/dyff/issues/173
I've added three options to `between` subcommand.
This feature is useful when you have a lot of things you want to filter or exclude.
* `--exclude`
* exclude reports from a set of differences based on supplied arguments
* `--filter-regexp`
* filter reports to a subset of differences based on supplied regular expressions
* `--exclude-regexp`
* exclude reports from a set of differences based on supplied regular expressions
> Add exclude option & filter or exclude by regular expression

- internal/cmd/root.go
- pkg/dyff/compare_test.go
- pkg/dyff/core.go
- Add implicit managedFields exclude
- Omit empty documents in Kubernetes compare
@dalbar FYI
> Fix Kubernetes file compare issue with empty documents

- assets/issues/issue-232/from.yml
- assets/issues/issue-232/to.yml
- internal/cmd/cmds_test.go
- pkg/dyff/reports.go
This hopefully solves [issue 232](https://github.com/homeport/dyff/issues/232). When comparing two YAMLs with a document removed and using the `--exclude` flag I noticed that dyff threw a panic. I think this is because those `Diff` objects don't have a `Path` set (must be `nil`) so when we do `--exclude` (or any of the other exclude/filter flags) it will panic trying to produce the report. Let me know if there is anything else you'd like me to do :)
> Ignore exclude/filter action if filterPath given is nil

- assets/issues/issue-232/from.yml
- assets/issues/issue-232/to.yml
- internal/cmd/cmds_test.go
- internal/cmd/common.go
- internal/cmd/root.go
- pkg/dyff/reports.go
Follow-up from PR #233
Combined commits from PR #233 to fix #232 as well as an internal fix to a inconsistency of the tool defaults, which differed between using `dyff` as a standalone binary versus using its core logic in a test case.
> Fix panic when using `--exclude` on reports with documents removed

- assets/issues/issue-243/from.yml
- assets/issues/issue-243/to.yml
- pkg/dyff/compare_test.go
- pkg/dyff/core.go
To compare maps on complex YAMLs, the library requires that
items are compared by finding a key to match elements on.  There
is a heuristic list of identifying keys that works in most cases.
This change enables additional keys to be explicitly added for
YAMLs that follow a known schema.
> Enable the addition of custom identifier keys

- internal/cmd/between.go
- internal/cmd/cmds_test.go
- internal/cmd/common.go
- pkg/dyff/core.go
Add flag to `between` command to specified an additional custom
identifier for the named-entry list processing.
> Introduce `--additional-identifier` flag

- .github/workflows/release.yml
- .goreleaser.yml
- README.md
Add Windows to the list of build operating systems.
Replace `--rm-dist` with `--clean` since it is deprecated.
Remove replacements that are deprecated.
> Enable Windows builds (again)

- go.mod
- go.sum
- internal/cmd/between.go
- internal/cmd/common.go
- internal/cmd/json.go
- internal/cmd/lastApplied.go
- internal/cmd/yaml.go
- pkg/dyff/core.go
Use `fmt.Errorf` or `bunt.Errorf` instead.
> Remove usage of deprecated `wrap.Error` function

- pkg/dyff/compare_test.go
- pkg/dyff/core.go
Add special logic to ensure that the various supported boolean value representations are treated the same. Closes #334
> Handle comparisons of boolean values correctly

- Makefile
I guess adding packages to the `go clean` command always actually cleaned the whole cache, so adding this parameter was made into an error.
cref: https://github.com/golang/go/issues/53725
> Package cleaning errors since golang 1.20

- .github/workflows/golangci-lint.yml
- .github/workflows/misspell.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
Bump Go to `1.23` in GitHub Actions for tests and builds.
> Bump Go version to `1.23`

- .github/workflows/golangci-lint.yml
- .github/workflows/misspell.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
Use `stable` as Go version.
Fix naming for linter job.
Remove unnecessary builds.
> Simplify GitHub Action setup

- internal/cmd/between.go
- internal/cmd/cmds_test.go
- internal/cmd/common.go
- pkg/dyff/compare_test.go
- pkg/dyff/reports.go
Sometimes it is useful to only include changes in structure and ignore the value changes. So I added a flag to drop such changes in the report.
--ignore-value-chnages
> feat(between): add ignore value changes flag

- .github/workflows/golangci-lint.yml
- .github/workflows/misspell.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
When using third-party actions, it is recommended to, [pin actions to a full length commit SHA](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) for security reasons.
The latest release of [actions/checkout@v4](https://github.com/actions/checkout/pull/1180) introduces the ability to add `ref: ${{ github.event.pull_request.head.sha }}`, allowing it to reference the most recent commit in a pull request.
> Add checked out ref for `actions/checkout@v4`

- assets/kubernetes/multi-docs-file-level/expected-dyff.human
- assets/kubernetes/multi-docs-file-level/from.yaml
- assets/kubernetes/multi-docs-file-level/to.yaml
- assets/kubernetes/rename/expected-dyff.human
- assets/kubernetes/rename/from.yaml
- assets/kubernetes/rename/from/kustomization.yaml
- assets/kubernetes/rename/from/pinniped.yaml
- assets/kubernetes/rename/to.yaml
- assets/kubernetes/rename/to/kustomization.yaml
- assets/kubernetes/rename/to/pinniped.yaml
- internal/cmd/cmds_test.go
- internal/cmd/common.go
- pkg/dyff/core.go
- pkg/dyff/output_human.go
- pkg/dyff/output_human_test.go
- pkg/dyff/rename/index.go
- pkg/dyff/rename/rename.go
- pkg/dyff/rename/util.go
- pkg/dyff/rename_detect.go
Hello!
This pull request adds git-like rename detection logic for Kubernetes documents comparison.
For now, I have implemented this only for Kubernetes resources, whose name "keys" can be computed from `metadata.name` and other fields.
This is because additions and deletions can be computed only if these "keys" are present.
The heuristic rename detection logic was mostly taken from https://github.com/go-git/go-git.
I would love to use this feature in my use-case, that is, using configMapGenerator with kustomize.
Currently, changing file contents a little bit results in a huge diff, because the kustomize adds hash suffix to resource names.
This use-case is added as a test case under `./assets/kubernetes/rename` directory.
Example of real-life use-case: …
> feat: Rename detection for Kubernetes resources

- .docs/commands/dyff.md
- .docs/commands/dyff_between.md
- .docs/commands/dyff_json.md
- .docs/commands/dyff_last-applied.md
- .docs/commands/dyff_version.md
- .docs/commands/dyff_yaml.md
- README.md
- cmd/gendoc/main.go
- go.mod
- go.sum
- internal/cmd/root.go
Add section with command-line tool command documentation.
Add tool to generate command-line tool command documentation.
Remove the `snap` section, since this is no longer maintained.
> Tweak README file

- internal/cmd/exitcode.go
- internal/cmd/root.go
Fixes: https://github.com/homeport/dyff/issues/448
Use `err.Error()` of `ExitCode` interface since this has a nil check.
Move `ExitCode` into its own source file.
Fix TYPO in comment about error.
> Fix panic when exit code does not have a cause

- internal/cmd/common.go
- pkg/dyff/core_suite_test.go
- pkg/dyff/output.go
- pkg/dyff/output_human.go
This makes it possible to copy the diffed lines without weird characters in them
> feat: allow disabling indent lines

- .docs/commands/dyff_between.md
- .docs/commands/dyff_last-applied.md
- internal/cmd/common.go
Use `reportOptions.useIndentLines` when generating reports.
Add new flag to generated Markdown documents.
> Fix new `--use-indent-lines` wiring in code
